export const ErrorMessage = {
  USER_NAME_HAS_BEEN_EXISTED: 'Tên tài khoản đã tồn tại',
  USER_NOT_FOUND: 'Không tìm thấy người dùng',
  INVALID_PASSWORD: 'Mật khẩu không hợp lệ',
  ACCOUNT_HAS_BEEN_LOCKED: 'Tài khoản đã bị khoá',
  ACCOUNT_HAS_BEEN_EXPIRED: 'Tài khoản đã hết hạn',
  ERROR_WHEN_SAVING_USER: 'Lỗi khi lưu user',
  ERROR_WHEN_UPDATING_USER: 'Lỗi khi cập nhật user',
  ERROR_WHEN_RETRIEVING_MODEL: 'Lỗi khi lấy model',
  ERROR_WHEN_COUNTING_MODEL: 'Lỗi khi đếm model',
  MODEL_NOT_FOUND: 'Không tìm thấy model',
  ERROR_WHEN_CREATING_MODEL: 'Lỗi khi tạo model',
  ERROR_WHEN_UPDATING_MODEL: 'Lỗi khi cập nhật model',
  ERROR_WHEN_REMOVING_MODEL: 'Lỗi khi xoá model',
  ERROR_WHEN_PROCESSING_REFRESH_TOKEN: 'Lỗi xử lý refresh token',
  ACCOUNT_HAS_BEEN_LOGIN: 'Tài khoản đã được đăng nhập trên thiết bị khác',
  LOGOUT_SUCCESSFULLY: 'Đăng xuất thành công',
  ERROR_WHEN_LOGOUT: 'Lỗi đăng xuất',
  ERROR_WHEN_GENERATING_TOKEN: 'Lỗi tạo token',
  UNAUTHORIZED: 'Không có quyền truy cập',
  LOGIN_FAILED: 'Đăng nhập thất bại',
};
export const ErrorMessageEN = {
  USER_NAME_HAS_BEEN_EXISTED: 'User name has been existed',
  USER_NOT_FOUND: 'User not found',
  INVALID_PASSWORD: 'Invalid password',
  ACCOUNT_HAS_BEEN_LOCKED: 'Account has been locked',
  ACCOUNT_HAS_BEEN_EXPIRED: 'Account has been expired',
  ERROR_WHEN_SAVING_USER: 'Error when saving new user',
  ERROR_WHEN_UPDATING_USER: 'Error when updating user',
  ERROR_WHEN_RETRIEVING_MODEL: 'Error when retrieving model',
  ERROR_WHEN_COUNTING_MODEL: 'Error when counting model',
  MODEL_NOT_FOUND: 'Model not found',
  ERROR_WHEN_CREATING_MODEL: 'Error when creating model',
  ERROR_WHEN_UPDATING_MODEL: 'Error when updating model',
  ERROR_WHEN_REMOVING_MODEL: 'Error when removing model',
  ERROR_WHEN_PROCESSING_REFRESH_TOKEN: 'Error when processing refresh token',
  ACCOUNT_HAS_BEEN_LOGIN: 'Your account has been used in another device',
  LOGOUT_SUCCESSFULLY: 'Logout successfully',
  ERROR_WHEN_LOGOUT: 'Error when logout',
  ERROR_WHEN_GENERATING_TOKEN: 'Error when generating token',
  UNAUTHORIZED: 'Unauthorized',
  LOGIN_FAILED: 'Login failed',
};
